PRN222.MilkTeaShop.Manager/Controllers/CombosController.cs
using System;
using System.Collections.Generic;
using System.Drawing.Printing;
using System.Linq;
using System.Threading.Tasks;
using CloudinaryDotNet;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using PRN222.MilkTeaShop.Manager.Models.Request;
using PRN222.MilkTeaShop.Manager.Models.Response;
using PRN222.MilkTeaShop.Repository.DbContexts;
using PRN222.MilkTeaShop.Repository.Models;
using PRN222.MilkTeaShop.Service.BusinessObjects;
using PRN222.MilkTeaShop.Service.Services;

namespace PRN222.MilkTeaShop.Manager.Controllers
{
    public class CombosController : Controller
    {
        private readonly IProductService _productService;
        private readonly CloudinaryService _cloudinaryService;
        public CombosController(IProductService productService, CloudinaryService cloudinaryService)
        {
            _productService = productService;
            _cloudinaryService = cloudinaryService;
        }

        // GET: Combos
        public async Task<IActionResult> Index(int? page,
            string? search)
        {
            int pageSize = 3;
            int pageNumber = (page ?? 1);

            var (products, totalItems) = await _productService.GetCombos(search, pageNumber, pageSize);
            ViewBag.CurrentPage = pageNumber;
            ViewBag.PageSize = pageSize;
            ViewBag.TotalItems = totalItems;
            ViewBag.Search = search;
            return View(products);
        }

		// GET: Combos/Create
		public async Task<IActionResult> Create()
		{

            var (milkteas, totalItems1) = await _productService.GetMilkTeas(null);
            var (toppings, totalItems2) = await _productService.GetToppings(null);

			var milkTeaViewModels = milkteas.Select(mt => new ProductViewModel
			{
				Id = mt.Id,
				Name = mt.Name,
				Price = null, // MilkTea không có giá trực tiếp
				ImageUrl = mt.ImageUrl,
				IsMilkTea = true,
				Sizes = mt.ProductSizes.Select(ps => new ProductSizeViewModel
				{
					SizeId = ps.SizeId,
					SizeName = ps.Size.Name,
					Price = ps.Price
				}).ToList()
			}).ToList();

			var toppingViewModels = toppings.Select(t => new ProductViewModel
			{
				Id = t.Id,
				Name = t.Name,
				Price = t.Price, // Topping có giá trực tiếp
				ImageUrl = t.ImageUrl,
				IsMilkTea = false,
				Sizes = new List<ProductSizeViewModel>() // Topping không có size
			}).ToList();

			List<ProductViewModel> productViewModels = milkTeaViewModels.Concat(toppingViewModels).ToList();
			ViewBag.Products = productViewModels;
			ViewBag.Milkteas = productViewModels.Where(p => p.IsMilkTea).ToList();
			ViewBag.Toppings = productViewModels?.Where(p => !p.IsMilkTea).ToList();

			return View();
		}

		// POST: Combos/Create
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Name,Description,Price,Image")] ComboCreationRequest request, [FromForm] string Products)
		{
			if (!string.IsNullOrEmpty(Products))
			{
				request.Products = JsonConvert.DeserializeObject<List<ProductInComboCreationRequest>>(Products);
			}
			else
			{
				request.Products = JsonConvert.DeserializeObject<List<ProductInComboCreationRequest>>(Products);

				var (milkteas, totalItems1) = await _productService.GetMilkTeas(null);
				var (toppings, totalItems2) = await _productService.GetToppings(null);

				var milkTeaViewModels = milkteas.Select(mt => new ProductViewModel
				{
					Id = mt.Id,
					Name = mt.Name,
					Price = null, // MilkTea không có giá trực tiếp
					ImageUrl = mt.ImageUrl,
					IsMilkTea = true,
					Sizes = mt.ProductSizes.Select(ps => new ProductSizeViewModel
					{
						SizeId = ps.SizeId,
						SizeName = ps.Size.Name,
						Price = ps.Price
					}).ToList()
				}).ToList();

				var toppingViewModels = toppings.Select(t => new ProductViewModel
				{
					Id = t.Id,
					Name = t.Name,
					Price = t.Price, // Topping có giá trực tiếp
					ImageUrl = t.ImageUrl,
					IsMilkTea = false,
					Sizes = new List<ProductSizeViewModel>() // Topping không có size
				}).ToList();

				List<ProductViewModel> productViewModels = milkTeaViewModels.Concat(toppingViewModels).ToList();
				ViewBag.Products = productViewModels;
				ViewBag.Milkteas = productViewModels.Where(p => p.IsMilkTea).ToList();
				ViewBag.Toppings = productViewModels?.Where(p => !p.IsMilkTea).ToList();
				return View(request);
			}

			string? imageUrl = null;
			if (request.Image != null && request.Image.Length > 0)
			{
				using var stream = request.Image.OpenReadStream();
				imageUrl = await _cloudinaryService.UploadImageAsync(stream, request.Name);
				if (imageUrl == null)
				{
					ModelState.AddModelError("Image", "Không thể tải ảnh lên.");
					return View(request);
				}
			}

			var model = new ComboModel
			{

				Name = request.Name,
				Description = request.Description,
				Price = request.Price,
				ImageUrl = imageUrl,
				Products = new List<ProductInCombo>()
			};

			if (request.Products != null)
			{
				foreach (var productRequest in request.Products)
				{
					var product = new ProductInCombo
					{
						Id = productRequest.ProductId,  
						Quantity = productRequest.Quantity, 
						Size = productRequest.SizeName 
					};
					model.Products.Add(product); 
				}
			}

			try{
				await _productService.CreateCombo(model);
			}
			catch (Exception e)
			{
				ViewBag.Error = e.Message;
			}
			return RedirectToAction(nameof(Index));
		}

        // GET: MilkTeas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();
            await _productService.Delete((int)id);
            return RedirectToAction(nameof(Index));
        }

        // GET: MilkTeas/Active/5	
        public async Task<IActionResult> Active(int? id)
        {
            if (id == null)
                return NotFound();
            await _productService.Active((int)id);
            return RedirectToAction(nameof(Index));
        }
    }
}

PRN222.MilkTeaShop.Manager/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using PRN222.MilkTeaShop.Service.Services;
using PRN222.MilkTeaShop.Service.Services.Interface;

namespace PRN222.MilkTeaShop.Manager.Controllers
{
    [Route("api/dashboard")]
    public class DashboardController : Controller
    {
        private readonly IDashboardService _dashboardService;

        public DashboardController(IDashboardService dashboardService)
        {
            _dashboardService = dashboardService;
        }
        public async Task<IActionResult> Index()
        {
            var dailyRevenue =  await _dashboardService.GetTotalRevenueByDay();
            var monthlyRevenue = await _dashboardService.GetTotalRevenueByMonth();
            var products = await _dashboardService.GetHighLightProduct();

            ViewBag.DailyRevenue = dailyRevenue;
            ViewBag.MonthyRevenue = monthlyRevenue;
            ViewBag.AnnualRevenue = monthlyRevenue;
            ViewBag.Products = products;
            return View();
        }

        [HttpGet("sales-data")]
        public async Task<IActionResult> GetSalesData()
        {
            var salesData = await _dashboardService.GetSalesData();
            return Ok(salesData);
        }
    }
}

PRN222.MilkTeaShop.Manager/Controllers/MilkTeasController.cs
using Microsoft.AspNetCore.Mvc;
using PRN222.MilkTeaShop.Manager.Models.Request;
using PRN222.MilkTeaShop.Service.BusinessObjects;
using PRN222.MilkTeaShop.Service.Services;

namespace PRN222.MilkTeaShop.Manager.Controllers
{
    public class MilkTeasController : Controller
    {
        private readonly IProductService _productService;
		private readonly CloudinaryService _cloudinaryService;

		public MilkTeasController(IProductService productService, CloudinaryService cloudinaryService)
        {
            _productService = productService;
            _cloudinaryService = cloudinaryService;
        }

        // GET: MilkTeas
        public async Task<IActionResult> Index(int? page,
            string? search)
        {
            int pageSize = 5;
            int pageNumber = (page ?? 1);

            var (products, totalItems) = await _productService.GetMilkTeas(search, pageNumber, pageSize);
            ViewBag.CurrentPage = pageNumber;
            ViewBag.PageSize = pageSize;
            ViewBag.TotalItems = totalItems;
            ViewBag.Search = search;
            return View(products);

        }

        // GET: MilkTeas/Create
        public async Task<IActionResult> Create()
        {
            return View();
        }

        // POST: MilkTeas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Description,PriceSizeS,PriceSizeM,PriceSizeL,Image")] MilkTeaCreationRequest request)
        {
            int categoryId = 1;

            string? imageUrl = null;

            if (request.Image != null && request.Image.Length > 0)
            {
                using var stream = request.Image.OpenReadStream();
                imageUrl = await _cloudinaryService.UploadImageAsync(stream, request.Name);
                if (imageUrl == null)
                {
                    ModelState.AddModelError("Image", "Không thể tải ảnh lên.");
                    return View(request);
                }
            }

            var model = new MilkTeaModel
            {
                Name = request.Name,
                Description = request.Description,
                ImageUrl = imageUrl,
                PriceSizeS = request.PriceSizeS,
                PriceSizeM = request.PriceSizeM,
                PriceSizeL = request.PriceSizeL
            };
            try
            {
                await _productService.CreateMilkTea(model);
			} catch (Exception e)
            {
				ViewBag.Error = e.Message;
			}

            return RedirectToAction(nameof(Index));
        }

        // GET: MilkTeas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var model = await _productService.GetMilkTea((int)id);

            if(model == null)
            {
                return NotFound();
            }

            var request = new MilkTeaUpdateRequest
            {
                Id = model.Id,
                Name = model.Name,
                Description = model.Description,
                PriceSizeS = model.PriceSizeS,
                PriceSizeM = model.PriceSizeM,
                PriceSizeL = model.PriceSizeL,
                ImageUrl = model.ImageUrl,
            };

            return View(request);
        }

        // POST: MilkTeas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("Id,Name,Description,PriceSizeS,PriceSizeM,PriceSizeL,Image")] MilkTeaUpdateRequest request)
        {
			if (request.Image != null && request.Image.Length > 0)
			{
                string? url = null; 
				using var stream = request.Image.OpenReadStream();
				url = await _cloudinaryService.UploadImageAsync(stream, request.Name);
				if (url == null)
				{
					ModelState.AddModelError("Image", "Không thể tải ảnh lên.");
					return View(request);
				}
                request.ImageUrl = url;
			}

			var model = new MilkTeaModel
			{
                Id = request.Id,
				Name = request.Name,
				Description = request.Description,
				ImageUrl = request.ImageUrl,
				PriceSizeS = request.PriceSizeS,
				PriceSizeM = request.PriceSizeM,
				PriceSizeL = request.PriceSizeL
			};
			try
			{
				await _productService.UpdateMilkTea(model);
			}
			catch (Exception e)
			{
				ViewBag.Error = e.Message;
			}

			return RedirectToAction(nameof(Index));
		}

        // GET: MilkTeas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();
            await _productService.Delete((int)id);
            return RedirectToAction(nameof(Index));
		}

		// GET: MilkTeas/Active/5	
		public async Task<IActionResult> Active(int? id)
		{
			if (id == null)
				return NotFound();
			await _productService.Active((int)id);
			return RedirectToAction(nameof(Index));
		}
	}
}

PRN222.MilkTeaShop.Manager/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PRN222.MilkTeaShop.Repository.DbContexts;
using PRN222.MilkTeaShop.Repository.Models;
using PRN222.MilkTeaShop.Service.Services;
using PRN222.MilkTeaShop.Service.Services.Interface;

namespace PRN222.MilkTeaShop.Manager.Controllers
{
    public class OrdersController : Controller
    {
        private readonly IOrderService _orderService;

        public OrdersController(IOrderService orderService)
        {
            _orderService = orderService;
        }

        // GET: Orders
        public async Task<IActionResult> Index(int? page,
            string? search)
        {
            int pageSize = 4;
            int pageNumber = (page ?? 1);

            var (orders, totalItems) = await _orderService.GetOrders(search, pageNumber, pageSize);
            ViewBag.CurrentPage = pageNumber;
            ViewBag.PageSize = pageSize;
            ViewBag.TotalItems = totalItems;
            ViewBag.Search = search;
            return View(orders);
        }

    }
}

PRN222.MilkTeaShop.Manager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PRN222.MilkTeaShop.Manager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PRN222.MilkTeaShop.Manager.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PRN222.MilkTeaShop.Manager</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - PRN222.MilkTeaShop.Manager - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PRN222.MilkTeaShop.Manager/Views/Shared/_ManagerLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lucky Tea Shop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/layout.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <div class="admin-container">
        <nav class="admin-sidebar">
            <h3>Lucky Milk Tea</h3>
            <ul>
                <li><a asp-controller="Dashboard"><i class="bi bi-speedometer2"></i> Dashboard</a></li>
                <li><a asp-controller="MilkTeas"><i class="bi bi-cup-straw"></i> Quản lý trà sữa</a></li>
                <li><a asp-controller="Toppings"><i class="bi bi-share"></i> Quản lý topping</a></li>
                <li><a asp-controller="Combos"><i class="bi bi-boxes"></i> Quản lý combo</a></li>
                <li><a asp-controller="Employees"><i class="bi bi-person-gear"></i>Quản lý nhân viên</a></li>
                <li><a asp-controller="Orders"><i class="bi bi-receipt"></i>Quản lý hóa đơn</a></li>
            </ul>
        </nav>
        <div class="admin-content">
            <div class="header d-flex justify-content-between align-items-center px-4">
                <div class="fs-3 fw-bold">@ViewData["HeaderTitle"]</div>
                <button class="btn btn-danger">Logout</button>
            </div>
            <main>
                @RenderBody()
            </main>
        </div>

    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>